version: "3.7"

services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: ROOTNAME
      MINIO_ROOT_PASSWORD: CHANGEME123
    volumes:
      - ./data:/data
    ports:
      - "9000:9000"
      - "3000:3000"
    command: server /data --console-address ":3000"
