apiVersion: v1
kind: Service
metadata:
  name: minio-console-service
spec:
  type: ClusterIP
  selector:
    app: minio
  ports:
  - name: console
    protocol: TCP
    port: 9001
    targetPort: 9001
  - name: api
    protocol: TCP
    port: 9000
    targetPort: 9000
