apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
type: Opaque
data:
  access-key: a2lQaXJIMUVOIDEyZzZ6b3NPb3Vk 
  secret-key: Q1JxdDV2eFFqUVpMZXphR2d0cm9ZeDlDUUNRcno4Mm5rWVdpTnBvUA== 
  root-user: Uk9PVE5BTUU=
  root-pwd: Q0hBTkdFTUUxMjM=