apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
data:
  rabbitmq-username: "Z3Vlc3Q="  # 'rabbitmquser' encoded in Base64
  rabbitmq-password: "Z3Vlc3Q="  # 'rabbitmqpass' encoded in Base64
